openapi: '3.1.0'
info:
    title: Carpooling
    version: '1.0.0'

paths:
    /user/auth:
        get:
            description: Returns information about authentication status
            responses:
                '200':
                    description: Information about authentication status
                    content:
                        application/json:
                            schema:
                                type: object
                                required:
                                    - userId
                                    - authenticated
                                properties:
                                    userId:
                                        type: integer
                                        format: int32
                                        default: -1
                                    authenticated:
                                        type: boolean
                                        default: false

    /user/{id}:
        get:
            summary: 'Get a user'
            description: 'Get a user by their user id'
            tags:
                - user
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      $ref: '#/components/schemas/Id'
                  description: 'The user ID'
            responses:
                '200':
                    description: 'Returns the user'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '404':
                    description: 'User not found'
        post:
            summary: 'Update a user'
            description: 'Update a user with new data, omitted fields are unchanged.'
            tags:
                - user
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      $ref: '#/components/schemas/Id'
                  description: 'The user ID'
            requestBody:
                description: 'The updated user object'
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    description: 'New email of the user'
                                friends:
                                    type: array
                                    description: 'New friend list of user'
                                    items:
                                        $ref: '#/components/schemas/Id'
            responses:
                '200':
                    description: 'Returns the updated user'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                '401':
                    description: 'Body is empty'
                '404':
                    description: 'User not found'

components:
    schemas:
        Id:
            type: number
            format: int32
            description: Database Ids
        User:
            type: object
            description: 'A user'
            properties:
                id:
                    $ref: '#/components/schemas/Id'
                    description: 'The ID of the user'
                first_name:
                    type: string
                    description: 'First name of the user'
                last_name:
                    type: string
                    description: 'Last name of the user'
                email:
                    type: string
                    description: 'Email of the user'
                date_of_birth:
                    type: date
                    description: 'Date of birth for this user'
                friends:
                    type: array
                    items:
                        type: string
                    description: List of friend ids
                    default: []
            required:
                - id
                - first_name
                - last_name
                - email
                - date_of_birth
                - friends
