openapi: '3.0.3'
info:
    title: 'Carpooling'
    version: '0.1.1'
paths:
    /user/authe:
        get:
            summary: 'Get auth status'
            description: 'Returns information about authentication status'
            responses:
                '200':
                    description: 'Information about authentication status'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/AuthInfo'
    /user/{id}:
        get:
            summary: 'Get a user'
            description: 'Get a user by their user id'
            tags:
                - user
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      $ref: 'definitions.yaml#/components/schemas/Id'
                  description: 'The user ID'
            responses:
                '200':
                    description: 'Returns the user'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/User'
                '400':
                    description: 'No id provided'
                '401':
                    description: 'Unauthenticated'
                '404':
                    description: 'User not found'

    /user:
        patch:
            summary: 'Update a user'
            description: 'Update a user with new data, omitted fields are unchanged.'
            tags:
                - user
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      $ref: 'definitions.yaml#/components/schemas/Id'
                  description: 'The user ID'
            requestBody:
                description: 'The updated user object'
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    description: 'New email of the user'
                                friends:
                                    type: array
                                    description: 'New friend list of user'
                                    items:
                                        $ref: 'definitions.yaml#/components/schemas/Id'
            responses:
                '200':
                    description: 'Returns the updated user'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/User'
                '401':
                    description: 'Unauthenticated'
                '404':
                    description: 'User not found'

        post:
            summary: 'Create a user'
            description: 'Create a user from the provided data and firebase auth token'
            tags:
                - user
            requestBody:
                description: 'User details'
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                firstName:
                                    type: string
                                    description: 'First name of the user'
                                lastName:
                                    type: string
                                    description: 'Last name of the user'
                                dateOfBirth:
                                    type: number
                                    description: 'Date of birth of the user'
                            required:
                                - firstName
                                - lastName
                                - dateOfBirth
            responses:
                '200':
                    description: 'Returns the newly created user'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/User'
                '401':
                    description: 'Unauthenticated'
                '409':
                    description: 'User already exists'

    /events/{id}:
        get:
            summary: 'Get event by id'
            description: 'Get a specific event by its id'
            tags:
                - event
            parameters:
                - in: path
                  name: id
                  schema:
                      $ref: 'definitions.yaml#/components/schemas/Id'
                  required: true
                  description: 'Id of the event to get'
            responses:
                '200':
                    description: 'Returns the event'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/Event'
                '401':
                    description: 'Unauthenticated'
                '404':
                    description: 'Event not found'

    /events:
        get:
            summary: 'List own events'
            description: 'List all events the current user is a owner or member of.'
            tags:
                - event
            responses:
                '200':
                    description: 'List of events'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/Event'
        post:
            summary: 'Create an event'
            description: 'Create a new event by a signed in user.'
            tags:
                - event
            requestBody:
                description: 'The event object'
                required: true
                content:
                    application/json:
                        schema:
                            $ref: 'definitions.yaml#/components/schemas/Event'
            responses:
                '200':
                    description: 'Returns the event id'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/Event'
                                description: 'The newly created event'
                '400':
                    description: 'Invalid body'
                '401':
                    description: 'Unauthenticated'

        patch:
            summary: 'Update an event'
            description: 'Update an existing event.'
            tags:
                - event
            requestBody:
                description: |
                    Fields to modify, non-existant fields lead to no change.
                    At least one field has to be provided.
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                    description: 'Title of the event'
                                description:
                                    type: string
                                    description: 'Description of the event'
                                startDateTime:
                                    type: integer
                                    format: int32
                                    description: 'Unix timestamp when the event starts'
                                endDateTime:
                                    type: integer
                                    format: int32
                                    description: 'Unix timestamp when the event ends'
                                members:
                                    type: string
                                    items:
                                        $ref: 'definitions.yaml#/components/schemas/Id'
                                    description: 'List of event members'
            responses:
                '200':
                    description: 'Returns the updated event'
                    content:
                        application/json:
                            schema:
                                $ref: 'definitions.yaml#/components/schemas/Event'
                '400':
                    description: 'Invalid body'
                '401':
                    description: 'Body is empty'
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: FBAuth

security:
    - bearerAuth: []
